import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-tertiary-container": "#706256",
              "tertiary": "#ffffff",
              "outline": "#8e9195",
              "on-primary-fixed": "#161c22",
              "on-error-container": "#ffdad6",
              "surface": "#131314",
              "on-secondary-container": "#a7b6cc",
              "primary-fixed-dim": "#c1c7cf",
              "on-secondary-fixed-variant": "#39485a",
              "background": "#131314",
              "tertiary-fixed-dim": "#d6c3b5",
              "on-primary-container": "#5f656c",
              "on-background": "#e5e2e2",
              "primary-fixed": "#dde3eb",
              "surface-tint": "#c1c7cf",
              "inverse-surface": "#e5e2e2",
              "surface-dim": "#131314",
              "on-secondary-fixed": "#0d1c2d",
              "on-surface": "#e5e2e2",
              "surface-variant": "#353535",
              "tertiary-fixed": "#f3dfd0",
              "error": "#ffb4ab",
              "on-error": "#690005",
              "primary": "#ffffff",
              "on-surface-variant": "#c5c6cb",
              "secondary-container": "#39485a",
              "on-secondary": "#233143",
              "on-tertiary-fixed": "#241a11",
              "error-container": "#93000a",
              "on-primary-fixed-variant": "#41474e",
              "inverse-primary": "#595f66",
              "secondary-fixed": "#d4e4fa",
              "surface-container-highest": "#353535",
              "surface-bright": "#393939",
              "tertiary-container": "#f3dfd0",
              "primary-container": "#dde3eb",
              "outline-variant": "#44474a",
              "secondary": "#b9c8de",
              "on-tertiary-fixed-variant": "#51443a",
              "inverse-on-surface": "#313031",
              "surface-container": "#201f20",
              "surface-container-high": "#2a2a2a",
              "surface-container-low": "#1b1b1c",
              "surface-container-lowest": "#0e0e0f",
              "on-tertiary": "#3a2e24",
              "secondary-fixed-dim": "#b9c8de",
              "on-primary": "#2b3137"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "unit": "4px",
              "container-max": "1440px",
              "margin": "24px",
              "gutter": "16px",
              "stack-md": "16px",
              "stack-lg": "32px",
              "stack-sm": "8px",
              "container-padding": "24px"
      },
      "fontFamily": {
              "body-lg": ["Geist", "sans-serif"],
              "code": ["JetBrains Mono", "monospace"],
              "headline-sm": ["Geist", "sans-serif"],
              "body-md": ["Geist", "sans-serif"],
              "headline-md": ["Geist", "sans-serif"],
              "headline-lg": ["Geist", "sans-serif"],
              "label-md": ["Geist", "sans-serif"],
              "title-sm": ["Geist", "sans-serif"],
              "body-sm": ["Geist", "sans-serif"],
              "code-mono": ["JetBrains Mono", "monospace"],
              "label-caps": ["Geist", "sans-serif"],
              "display-lg": ["Geist", "sans-serif"]
      },
      "fontSize": {
              "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400" }],
              "code": ["13px", { "lineHeight": "18px", "letterSpacing": "0", "fontWeight": "400" }],
              "headline-sm": ["18px", { "lineHeight": "26px", "letterSpacing": "0", "fontWeight": "500" }],
              "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400" }],
              "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
              "headline-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
              "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
              "title-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
              "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
              "code-mono": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
              "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
              "display-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [forms, containerQueries],
}
